export const SET_QUIZ_ANSWER_STATE = "@quiz/SET_QUIZ_ANSWER_STATE";

export const GET_SAVED_QUIZZES_REQUEST = "@quiz/GET_SAVED_QUIZZES_REQUEST";
export const SET_SAVED_QUIZZES_SUCCESS = "@quiz/SET_SAVED_QUIZZES_SUCCESS";
export const DELETE_SAVED_QUIZ_SUCCESS = "@quiz/DELETE_SAVED_QUIZ_SUCCESS";
export const SET_SAVED_QUIZZES_SORT_BY_STATE = "@quiz/SET_SAVED_QUIZZES_SORT_BY_STATE";
