export const SET_FILTER_REQUEST_STATE = "@provider/SET_FILTER_REQUEST_STATE";
export const GET_FILTER_SEARCH_REQUEST = "@provider/GET_FILTER_SEARCH_REQUEST";
export const SET_FILTER_SEARCH_STATE = "@provider/SET_FILTER_SEARCH_STATE";

export const SET_FILTER_STATE = "@provider/SET_FILTER_STATE";

export const GET_SAVED_LISTING_REQUEST = "@provider/GET_SAVED_LISTING_REQUEST";
export const SET_SAVED_LISTING_SUCCESS = "@provider/SET_SAVED_LISTING_SUCCESS";
export const SET_SAVED_LISTING_SORT_BY_STATE = "@provider/SET_SAVED_LISTING_SORT_BY_STATE";
export const SET_SELECTED_SAVED_LISTING_STATE = "@provider/SET_SELECTED_SAVED_LISTING_STATE";

export const GET_SAVED_CLIENT_REQUEST = "@provider/GET_SAVED_CLIENT_REQUEST";
export const SET_SAVED_CLIENT_SUCCESS = "@provider/SET_SAVED_CLIENT_SUCCESS";
export const SET_SAVED_CLIENT_FILTER_BY_STATE = "@provider/SET_SAVED_CLIENT_FILTER_BY_STATE";

export const GET_PROVIDER_DETAILS_REQUEST = "@provider/GET_PROVIDER_DETAILS_REQUEST";
export const SET_PROVIDER_DETAILS_SUCCESS = "@provider/SET_PROVIDER_DETAILS_SUCCESS";

export const GET_APPOINTMENTS_REQUEST = "@provider/GET_APPOINTMENTS_REQUEST";
export const SET_APPOINTMENTS_SUCCESS = "@provider/SET_APPOINTMENTS_SUCCESS";
export const SET_APPOINTMENTS_FILTER_BY_STATE = "@provider/SET_APPOINTMENTS_FILTER_BY_STATE";

export const GET_SAVED_SEARCHES_REQUEST = "@provider/GET_SAVED_SEARCHES_REQUEST";
export const SET_SAVED_SEARCHES_SUCCESS = "@provider/SET_SAVED_SEARCHES_SUCCESS";
export const SET_SAVED_SEARCHES_SORT_BY_STATE = "@provider/SET_SAVED_SEARCHES_SORT_BY_STATE";
export const DELETE_SAVED_SEARCH_SUCCESS = "@provider/DELETE_SAVED_SEARCH_SUCCESS";
