export const SET_AUTH_STATE = "@auth/SET_AUTH_STATE";
export const SET_ROUTE_SHARE_STATE = "@auth/SET_ROUTE_SHARE_STATE";
export const SET_SIGNUP_PROVIDER_REQUEST_STATE = "@auth/SET_SIGNUP_PROVIDER_REQUEST_STATE";
export const RESET_SIGNUP_PROVIDER_REQUEST_STATE = "@auth/RESET_SIGNUP_PROVIDER_REQUEST_STATE";
export const SET_SIGNUP_USER_REQUEST_STATE = "@auth/SET_SIGNUP_USER_REQUEST_STATE";
export const RESET_SIGNUP_USER_REQUEST_STATE = "@auth/RESET_SIGNUP_USER_REQUEST_STATE";
export const SET_USER_STATE = "@auth/SET_USER_STATE";

export const GET_USER_PROFILE_REQUEST = "@auth/GET_USER_PROFILE_REQUEST";
export const SET_USER_PROFILE_STATE = "@auth/SET_USER_PROFILE_STATE";

export const GET_ORGANIZATION_REQUEST = "@auth/GET_ORGANIZATION_REQUEST";
export const SET_ORGANIZATION_STATE = "@auth/SET_ORGANIZATION_STATE";

export const GET_SITES_REQUEST = "@auth/GET_SITES_REQUEST";
export const SET_SITES_STATE = "@auth/SET_SITES_STATE";

export const GET_ADDITAIONAL_MEMBERS_REQUEST = "@auth/GET_ADDITAIONAL_MEMBERS_REQUEST";
export const SET_ADDITAIONAL_MEMBERS_STATE = "@auth/SET_ADDITAIONAL_MEMBERS_STATE";
export const DELETE_ADDITIONAL_MEMEMBER_SUCCESS = "@auth/DELETE_ADDITIONAL_MEMEMBER_SUCCESS";
