export const GET_CARE_SUBCATEGORIES_REQUEST = "@category/GET_CARE_SUBCATEGORIES_REQUEST";
export const SET_CARE_SUBCATEGORIES_STATE = "@category/SET_CARE_SUBCATEGORIES_STATE";

export const GET_SPECIAL_QUALIFICATIONS_REQUEST = "@category/GET_SPECIAL_QUALIFICATIONS_REQUEST";
export const SET_SPECIAL_QUALIFICATIONS_STATE = "@category/SET_SPECIAL_QUALIFICATIONS_STATE";
